### ISSUE TITLE
GMagick support

### ISSUE THREAD

**Issue by agentile** [ksubileau/color-thief-php#15]
Would you be so kind as to support graphics magick in the future? Thank you.

**Comment by ksubileau** [comment]
I finally managed to get the pixel colors with Gmagick:
```php
$cropped = clone $image;
$histogram = $cropped->cropImage(1, 1, $x, $y)->getImageHistogram();
$pixel = array_shift($histogram);
$colorArray = $pixel->getColor(true, true);
```
[Imagine](https://github.com/avalanche123/Imagine/blob/59d5f94e11cea154e7f306443515432307acf81e/lib/Imagine/Gmagick/Image.php#L546) (a popular PHP library for image processing) also uses this method to get pixel colors.
Surprisingly I didn't notice an excessive memory or time consumption. I get almost the same performances than Imagick.
