### ISSUE TITLE
leaking memory while processing many files

### ISSUE THREAD

**Issue by patsplat** [ksubileau/color-thief-php#17]
Have encountered many memory errors while processing a directory of many files (3188 jpegs total).  Memory usage steadily increases when ColorThief::getPalette is called until a large file causes a memory error.  Profiling using pecl memprof shows that the most memory usage is occuring within color thief.

On my machine, adding the following appears to have improved the ability for PHP to garbage collect:

* static::getPalette ```$pixelArray = null;```
* static::quantize ```$histo = null;```

See below for placement.  Still testing to confirm.

    public static function getPalette($sourceImage, $colorCount = 10, $quality = 10, array $area = null)
    {
        // short-circuit
        if ($colorCount < 2 || $colorCount > 256) {
            throw new \InvalidArgumentException("The number of palette colors must be between 2 and 256 inclusive.");
        }
        // short-circuit
        if ($quality < 1) {
            throw new \InvalidArgumentException("The quality argument must be an integer greater than one.");
        }

        $pixelArray = static::loadImage($sourceImage, $quality, $area);
        if (!count($pixelArray)) {
            throw new \RuntimeException("Unable to compute the color palette of a blank or transparent image.", 1);
        }

        // Send array to quantize function which clusters values
        // using median cut algorithm
        $cmap = static::quantize($pixelArray, $colorCount);
        $palette = $cmap->palette();

        $pixelArray = null;
        return $palette;
    }

    private static function quantize($pixels, $maxcolors)
    {
        // short-circuit
        if (! count($pixels) || $maxcolors < 2 || $maxcolors > 256) {
            // echo 'wrong number of maxcolors'."\n";
            return false;
        }

        $histo = static::getHisto($pixels);

        // check that we aren't below maxcolors already
        //if (count($histo) <= $maxcolors) {
            // XXX: generate the new colors from the histo and return
        //}

        $vbox = static::vboxFromHistogram($histo);

        $pq = new PQueue(function ($a, $b) {
            return ColorThief::naturalOrder($a->count(), $b->count());
        });
        $pq->push($vbox);

        // first set of colors, sorted by population
        static::quantizeIter($pq, self::FRACT_BY_POPULATIONS * $maxcolors, $histo);

        // Re-sort by the product of pixel occupancy times the size in color space.
        $pq->setComparator(function ($a, $b) {
            return ColorThief::naturalOrder($a->count() * $a->volume(), $b->count() * $b->volume());
        });

        // next set - generate the median cuts using the (npix * vol) sorting.
        static::quantizeIter($pq, $maxcolors - $pq->size(), $histo);

        // calculate the actual colors
        $cmap = new CMap();

        for ($i = $pq->size(); $i > 0; $i--) {
            $cmap->push($pq->pop());
        }
        $histo = null;
        
        return $cmap;
    }

**Comment by patsplat** [comment]
Testing this change on my full dataset:

https://github.com/patsplat/color-thief-php/commit/a21089d941eea0b5721887d71ccd695bdda0728f

As this change is somewhat speculative will generate pull request only if there are no memory errors.

**Comment by ksubileau** [comment]
Which version of PHP are you running ? Are all the images are the same width and height ? 
Does the execution always stops at the same image or randomly ?
Maybe you could also try adding more "= null" elsewhere ?

**Comment by patsplat** [comment]
*Which version of PHP are you running?*

Homebrew php56 on Yosemite

*Do all the images have the same width and height?*

Input dimensions vary

*Does the execution always stops at the same image or quite randomly?*

Stopping point appears to be random

*Maybe you could also try adding more "= null" elsewhere ?
And what about unset() instead of "= null" ?*

Will do.  Thus far, addition of those two lines appears to be enough to change the behavior.  Memory consumption appearing to spike up and down rather than just up.

**Comment by patsplat** [comment]
Process is part of a data migration.  Entire run takes time.  If completed would validate that garbage collection was improved by the patch.

**Comment by patsplat** [comment]
Still running, looking promising.

**Comment by patsplat** [comment]
The memory was leaking in the enclosing loop.  It was erroneously attributed perhaps b/c the values were initially constructed in color-thief-php.  Using unset() and gc_collect_cycles() in the enclosing loop corrected the issue.  Tested with the latest released version.

Might be worth noting in the documentation, but there will be no change to be pulled.

Thanks for your help, including the suggestion regarding unset()
