### ISSUE TITLE
How to use it outside Yii & without composer

### ISSUE THREAD

**Issue by abdelhady** [ksubileau/color-thief-php#18]
It is not an issue, but just a question,

It is an awesome library, good job :) , but how to use this library outside Yii & without composer? I mean is it possible to use it in any kind of PHP projects and how?

Thanks.

**Comment by ksubileau** [comment]
To use it outside Yii... In fact, I didn't know what Yii was until now :). So there is absolutely no dependencies between Yii (or another PHP framework) and this library.

You can also use it without composer, but you will have to require all the php files of the library manually (except those in the tests folder of course).

**Comment by abdelhady** [comment]
Oops :) , I got confused due to a legacy project I'm working on, thanks a lot.
