### ISSUE TITLE
Palette sometimes returns 256 for channels

### ISSUE THREAD

**Issue by finwe** [ksubileau/color-thief-php#24]
For [this image](https://scontent-fra3-1.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/12276911_1702154443353740_1257274370_n.jpg), the getPalette method returns 256 for the blue channel in colors 8 and 9

```
  ...
  [7]=>
  array(3) {
    [0]=>
    int(248)
    [1]=>
    int(252)
    [2]=>
    int(256)
  }
  [8]=>
  array(3) {
    [0]=>
    int(248)
    [1]=>
    int(252)
    [2]=>
    int(256)
  }
}
```

For [this one](https://scontent-fra3-1.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/12353269_458736790998840_1123451380_n.jpg) it returns 256 in the red channel.

The channel value should always be <= 255.

**Comment by ksubileau** [comment]
Fixed !
Thank you for this bug report :)
