### ISSUE TITLE
error in doc, left bottom in fact, not left top

### ISSUE THREAD

**Issue by Zhanat87** [ksubileau/color-thief-php#32]
error in doc, left bottom in fact, not left top.
so if img was 800/600 and need color from center, need set:
$color = ColorThief::getColor($path, 10, ['x' => 200, 'y' => 150, 'w' => 400, 'h' => 300])
not:
$color = ColorThief::getColor($path, 10, ['x' => 200, 'y' => 450, 'w' => 400, 'h' => 300]).

need feex it in doc.
https://github.com/ksubileau/color-thief-php/blob/master/lib/ColorThief/ColorThief.php#L189

**Comment by ksubileau** [comment]
Hello,

Sorry but I think you're wrong, the reference point for the inner area to analyse is at the top left as written in the documentation. But be careful, as usual in image and video processing, the reference point of the coordinate system is also the top left pixel of the image. Here is an illustration of what is happening : 

![example](https://cloud.githubusercontent.com/assets/3837104/23568956/605ae370-005d-11e7-9a44-b01d716b008e.png)

But maybe I could complete the documentation to specify explicitly the origin of the coordinate system 👍
