### ISSUE TITLE
Server crash on Windows with relative paths

### ISSUE THREAD

**Issue by ShiraMiyuko** [ksubileau/color-thief-php#35]
I use this library without problems 6 months ago on Codeigniter with manual includes, but now I add it to composer and server crash on loop when I try to use it on my localhost.

Server details:
* ColorThief version 1.3.1
* PHP Version 7.1.11 x64 Thread Safe
* Apache/2.4.25 (Win64)

No errors showed, just crash the server when I call a function from the library:

`ColorThief::getColor('assets/image/example.jpg')`

Tested other composer libraries without problems.

**Comment by ShiraMiyuko** [comment]
Ok, I found more info about the crash, if I call:
`ColorThief::getColor('assets/image/example.jpg')`
Server crash on loop and close connection after some retries.
-----

If I call:
`ColorThief::getColor('/assets/image/example.jpg')`
Report error that file don't exist or are not readable.
-----

If I call:
`ColorThief::getColor(FC_PATH . 'assets/image/example.jpg')`
Work fine without errors and no crashes.

Note: FC_PATH its a Codeigniter define for Root folder, it's likely full path or absolute path to websyte folder

**Comment by ksubileau** [comment]
Sorry, I can't reproduce the issue. Is it still relevant ?
