### ISSUE TITLE
getPalette() does not always return the requested amount of colors

### ISSUE THREAD

**Issue by ksubileau** [ksubileau/color-thief-php#5]
The function returns +/- 2 colors around the requested amount.

This bug comes from the original JS version : see lokesh/color-thief#19

**Comment by HorlogeSkynet** [comment]
Well, since 2014, it has not evolved

**Comment by ksubileau** [comment]
It looks like this bug has finally been fixed in the original library (see previously linked issue). If so, we should see if we can reproduce the fix here.

I notice [some users](https://github.com/spacecatninja/craft-imager-x/blob/8af747ee050e3416e03fff1dc182f7fe5373adf0/src/services/ImagerColorService.php#L116) are using a hack to fix this problem.
