### ISSUE TITLE
Support PHP 8.x

### ISSUE THREAD

**Issue by ksubileau** [ksubileau/color-thief-php#50]
- [x] Add tests against PHP 8.x
- [x] Update composer & README
- [x] Support objects instead of resources (see #48)

**Comment by stefanschindler** [comment]
Hi @ksubileau , any updates on PHP 8 support? I would highly appreciate that.

**Comment by ksubileau** [comment]
It's almost done in the v2.0 branch, but I still have some work to do for this release. I hope to be able to do it in a few days-weeks.
Meanwhile, you can start developing with the v2.0 branch, and I'll appreciate your feedback to let me know if everything is working as expected!

**Comment by stefanschindler** [comment]
Thank you very much, I will do that. The first tests with this branch showed, that everything works as expected.
