### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by ksubileau** [ksubileau/color-thief-php#7]
Currently, it seems unfortunately that the Javascript version is quite a lot faster and more efficient than this PHP port. 

As I'm not a PHP optimization specialist, any proposal (comment or pull request) in order to improve performance (memory consumption and/or computation time) is welcomed !

**Comment by FranceX** [comment]
Is there any improvement on the performance coming up? Or tricks to improve it,  i'm getting about .9s per image...

**Comment by ksubileau** [comment]
Unfortunately, no performance improvements is planned for now. In fact, I admit I don't really have any idea on how to improve it. So proposals are still welcomed !
But maybe you can use HHVM or wait for PHP 7 :)

**Comment by ksubileau** [comment]
The release 1.4.1 is out today with some significant performance improvements, thank to the @mreiden's work.
Even if some further improvements may be still possible, we have now reached a very good performance level, so I'll close this issue.
